"""Add unified sync fields for Tidal-Filesystem synchronization.

Revision ID: 987ed04d1693
Revises:
Create Date: 2025-11-21 23:24:06.153755
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "987ed04d1693"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tidal_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creator_name", sa.String(length=200), nullable=True),
        sa.Column("creator_id", sa.String(length=100), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("num_tracks", sa.Integer(), nullable=True),
        sa.Column("num_videos", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("picture_url", sa.String(length=500), nullable=True),
        sa.Column("square_picture_url", sa.String(length=500), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("last_item_added_at", sa.DateTime(), nullable=True),
        sa.Column("share_url", sa.String(length=500), nullable=True),
        sa.Column("listen_url", sa.String(length=500), nullable=True),
        sa.Column("local_folder_path", sa.String(length=1000), nullable=True),
        sa.Column("rekordbox_playlist_id", sa.String(length=255), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("last_updated_tidal", sa.DateTime(), nullable=True),
        sa.Column("last_synced_filesystem", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_in_tidal", sa.DateTime(), nullable=True),
        sa.Column("track_count_tidal", sa.Integer(), nullable=False),
        sa.Column("track_count_local", sa.Integer(), nullable=False),
        sa.Column("track_count_rekordbox", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlists_name"), "playlists", ["name"], unique=False)
    op.create_index(
        op.f("ix_playlists_sync_status"), "playlists", ["sync_status"], unique=False
    )
    op.create_index(
        op.f("ix_playlists_tidal_id"), "playlists", ["tidal_id"], unique=True
    )
    op.create_table(
        "sync_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_type", sa.String(length=20), nullable=False),
        sa.Column("snapshot_data", sa.Text(), nullable=False),
        sa.Column("playlist_count", sa.Integer(), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_type_created",
        "sync_snapshots",
        ["snapshot_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tidal_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("artist", sa.String(length=500), nullable=False),
        sa.Column("album", sa.String(length=500), nullable=True),
        sa.Column("album_artist", sa.String(length=500), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("isrc", sa.String(length=20), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("volume_number", sa.Integer(), nullable=True),
        sa.Column("explicit", sa.Boolean(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("copyright", sa.Text(), nullable=True),
        sa.Column("tidal_release_date", sa.DateTime(), nullable=True),
        sa.Column("audio_quality", sa.String(length=50), nullable=True),
        sa.Column("audio_modes", sa.String(length=100), nullable=True),
        sa.Column("version", sa.String(length=200), nullable=True),
        sa.Column("album_upc", sa.String(length=50), nullable=True),
        sa.Column("album_release_date", sa.DateTime(), nullable=True),
        sa.Column("album_cover_url", sa.String(length=500), nullable=True),
        sa.Column("normalized_name", sa.String(length=1000), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("file_format", sa.String(length=10), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("file_last_modified", sa.DateTime(), nullable=True),
        sa.Column("download_status", sa.String(length=20), nullable=False),
        sa.Column("download_error", sa.Text(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("rekordbox_content_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_in_tidal", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_artist_title", "tracks", ["artist", "title"], unique=False)
    op.create_index("idx_normalized_name", "tracks", ["normalized_name"], unique=False)
    op.create_index(
        op.f("ix_tracks_download_status"), "tracks", ["download_status"], unique=False
    )
    op.create_index(op.f("ix_tracks_file_path"), "tracks", ["file_path"], unique=False)
    op.create_index(
        op.f("ix_tracks_normalized_name"), "tracks", ["normalized_name"], unique=False
    )
    op.create_index(op.f("ix_tracks_tidal_id"), "tracks", ["tidal_id"], unique=True)
    op.create_table(
        "playlist_tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("in_tidal", sa.Boolean(), nullable=False),
        sa.Column("in_local", sa.Boolean(), nullable=False),
        sa.Column("in_rekordbox", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("symlink_path", sa.String(length=1000), nullable=True),
        sa.Column("symlink_valid", sa.Boolean(), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.Column("added_to_tidal", sa.DateTime(), nullable=True),
        sa.Column("added_to_local", sa.DateTime(), nullable=True),
        sa.Column("added_to_rekordbox", sa.DateTime(), nullable=True),
        sa.Column("removed_from_tidal", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_id", "track_id", name="uq_playlist_track"),
    )
    op.create_index("idx_playlist", "playlist_tracks", ["playlist_id"], unique=False)
    op.create_index(
        "idx_sync_state",
        "playlist_tracks",
        ["in_tidal", "in_local", "in_rekordbox"],
        unique=False,
    )
    op.create_index("idx_track", "playlist_tracks", ["track_id"], unique=False)
    op.create_index(
        op.f("ix_playlist_tracks_sync_status"),
        "playlist_tracks",
        ["sync_status"],
        unique=False,
    )
    op.create_table(
        "sync_operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=True),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("target", sa.String(length=20), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_operations_created_at"),
        "sync_operations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operations_operation_type"),
        "sync_operations",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operations_status"), "sync_operations", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_operations_status"), table_name="sync_operations")
    op.drop_index(
        op.f("ix_sync_operations_operation_type"), table_name="sync_operations"
    )
    op.drop_index(op.f("ix_sync_operations_created_at"), table_name="sync_operations")
    op.drop_table("sync_operations")
    op.drop_index(op.f("ix_playlist_tracks_sync_status"), table_name="playlist_tracks")
    op.drop_index("idx_track", table_name="playlist_tracks")
    op.drop_index("idx_sync_state", table_name="playlist_tracks")
    op.drop_index("idx_playlist", table_name="playlist_tracks")
    op.drop_table("playlist_tracks")
    op.drop_index(op.f("ix_tracks_tidal_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_normalized_name"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_file_path"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_download_status"), table_name="tracks")
    op.drop_index("idx_normalized_name", table_name="tracks")
    op.drop_index("idx_artist_title", table_name="tracks")
    op.drop_table("tracks")
    op.drop_index("idx_type_created", table_name="sync_snapshots")
    op.drop_table("sync_snapshots")
    op.drop_index(op.f("ix_playlists_tidal_id"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_sync_status"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_name"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
